const mongoose = require('mongoose');

const setupSchema = new mongoose.Schema({
    guildID: { type: String },
    saludosEnabled: { type: Boolean },
    saludosPalabra: { type: String },
    saludosMensaje: { type: String },
    recordatorioEnabled: { type: Boolean },
    recordatorioChannel: { type: String },
    recordatorioDescription: { type: String },
    recordatorioCantidad: { type: Number },
    logscanalcreado: { type: String },
    logsEnabled: {type: Boolean},
    logsChannel: { type: String },
    welcomeChannel: { type: String },
    welcomeEnabled: {type: Boolean},
    welcomeMensaje: { type: String },
    welcomeTime: { type: Number },
    sugerenciasEnabled: { type: Boolean },
    sugerenciasChannel: { type: String },
    confesionesEnabled: { type: Boolean },
    confesionesChannel: { type: String },
    linksEnabled: { type: Boolean },
    allowedRoles: [{ type: String, ref: 'Role' }],
    allowedUsers: [{ type: String, ref: 'User' }],
    bienvenidasChannel: { type: String },
    bienvenidasEnabled: {type: Boolean},
    bienvenidasMSG: { type: String },
    bienvenidasUSER: { type: String },
    bienvenidasCOUNT: { type: String },
    bienvenidasFONDO: { type: String, default: 'https://s1.1zoom.me/b5050/29/375109-blackangel_1366x768.jpg' },
    bienvenidasCIRCULO: { type: String, default: '#FFF' },
    bienvenidasTEXTO1: { type: String, default: '#FFF' },
    bienvenidasTEXTO2: { type: String, default: '#FFF' },
    bienvenidasTEXTO3: { type: String, default: '#FFF' },
    bienvenidasTITULO: { type: String },
    bienvenidasDESCRIPCION: { type: String },
    bienvenidasCOLOR: { type: String },
    despedidasChannel: { type: String },
    despedidasEnabled: {type: Boolean},
    despedidasMSG: { type: String },
    despedidasUSER: { type: String },
    despedidasCOUNT: { type: String },
    despedidasFONDO: { type: String, default: 'https://s1.1zoom.me/b5050/29/375109-blackangel_1366x768.jpg' },
    despedidasCIRCULO: { type: String, default: '#FFF' },
    despedidasTEXTO1: { type: String, default: '#FFF' },
    despedidasTEXTO2: { type: String, default: '#FFF' },
    despedidasTEXTO3: { type: String, default: '#FFF' },
    despedidasTITULO: { type: String },
    despedidasDESCRIPCION: { type: String },
    despedidasCOLOR: { type: String },
    deleteEnabled: { type: Boolean },
})

const model = mongoose.model("setupconfig", setupSchema);

module.exports = model;

